### ISSUE TITLE
Improve directions for sending crash log

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Polyfrost/CrashPatch#9]
Currently CrashPatch's biggest issue is people just screenshotting the GUI and literally not saying anything else, expecting me (or support staff i dont do tickets anymore) to use my prophetic abilities to figure out the issue. I hate doing support. This is not an issue inherent to CrashPatch, but it could be alleviated.

The top text tells you to follow the tips below and/or join the discord server and make a support ticket. This is then duplicated below, but without the support ticket part. Usually this process would be fine. SkyAnswers is supposed to walk people through sending their crash log. Great! The issue again stems from the fact that literacy is dead. At the bottom message by the Discord link, it should reiterate that they should make a support ticket, as to hopefully make them not post their lone screenshot in general (they still will regardless of instructions).

It may also help to make the crash log button more visible. Just had this issue in SkyClient (#general channel, of course) where I told someone to send the crash log and they replied with "what crash log".

Additionally, it may also be useful to do something like what Skytils does, where it prints the message in the vanilla crash report screen something along the lines of "Screenshotting this screen provides no useful information to any developers." Of course, the fact I know that line exists despite me not using Skytils means a lot, but it may still help some people to realize they should send the crash report and not a screenshot.

**Comment by Wyvest** [comment]
Make this a suggestion in the discord
